@extends('layouts.back.master')

@section('title', 'Detail Quotation')

@section('content')
    <div class="page-header d-print-none"><div class="container-xl"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Quotation</div><h1 class="page-title">{{ $quotation->subject }}</h1></div><div class="col-auto ms-auto d-flex gap-2">@can('preview', $quotation)<a class="btn" target="_blank" href="{{ route('quotations.preview', $quotation) }}">Preview draft</a>@endcan @can('update', $quotation)<a class="btn btn-primary" href="{{ route('quotations.edit', $quotation) }}">Edit draft</a>@endcan</div></div></div></div>
    <div class="page-body"><div class="container-xl"><div class="row g-3">
        @if($quotation->status === 'draft')
            <div class="col-12"><div class="card"><div class="card-body d-flex align-items-center gap-2"><div class="me-auto"><strong>Draft siap diproses?</strong><div class="text-secondary">Mode approval: {{ $quotation->approval_mode === 'direct' ? 'Direct' : 'Maker-checker' }}. Nomor baru diterbitkan ketika quotation complete.</div></div>
                @if($quotation->approval_mode === 'direct')
                    @can('completeDirect', $quotation)<form method="POST" action="{{ route('quotations.complete', $quotation) }}" onsubmit="return confirm('Complete quotation dan terbitkan nomor resmi sekarang?')">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><button class="btn btn-success">Complete & terbitkan nomor</button></form>@endcan
                @else
                    @can('submit', $quotation)<form method="POST" action="{{ route('quotations.submit', $quotation) }}">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><button class="btn btn-primary">Ajukan approval</button></form>@endcan
                @endif
            </div></div></div>
        @elseif($quotation->status === 'pending_approval')
            <div class="col-12"><div class="card"><div class="card-body"><div class="d-flex align-items-center gap-2"><div class="me-auto"><strong>Menunggu approval</strong><div class="text-secondary">Diajukan oleh {{ $quotation->submitter?->name }}.</div></div>@can('approve', $quotation)<form method="POST" action="{{ route('quotations.approve', $quotation) }}" onsubmit="return confirm('Setujui quotation dan terbitkan nomor resmi?')">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><button class="btn btn-success">Approve & complete</button></form>@endcan</div>
                @can('reject', $quotation)<form method="POST" action="{{ route('quotations.reject', $quotation) }}" class="mt-3">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><div class="input-group"><input class="form-control" name="reason" minlength="10" maxlength="5000" required placeholder="Alasan penolakan (minimal 10 karakter)"><button class="btn btn-outline-danger">Reject</button></div></form>@endcan
            </div></div></div>
        @elseif($quotation->status === 'rejected')
            <div class="col-12"><div class="alert alert-danger mb-0"><strong>Quotation ditolak.</strong> {{ $quotation->rejection_reason }} @can('update', $quotation)<a href="{{ route('quotations.edit', $quotation) }}" class="alert-link">Revisi draft</a>@endcan</div></div>
        @elseif($quotation->status === 'complete')
            @can('void', $quotation)<div class="col-12"><form method="POST" action="{{ route('quotations.void', $quotation) }}" class="card" onsubmit="return confirm('Void quotation dan nomor resminya? Nomor tetap tercatat dan tidak dapat digunakan ulang.')">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><div class="card-body"><div class="row g-2 align-items-end"><div class="col"><label class="form-label" for="void_reason">Alasan void</label><textarea id="void_reason" name="reason" class="form-control" minlength="5" maxlength="2000" required></textarea></div><div class="col-auto"><button class="btn btn-danger">Void quotation</button></div></div><div class="form-hint">Quotation complete immutable. Void tidak menghapus atau memakai ulang nomor.</div></div></form></div>@endcan
        @endif
        @php($pdfFile = $quotation->generatedFiles->firstWhere('kind', 'quotation_pdf'))
        @if(in_array($quotation->status, ['complete', 'void'], true))
            @can('viewPdf', $quotation)
                <div class="col-12"><div class="card"><div class="card-body d-flex align-items-center gap-3"><div class="me-auto"><strong>PDF quotation resmi</strong><div class="text-secondary">Status: {{ $pdfFile ? str($pdfFile->status)->headline() : 'Belum tersedia' }}@if($pdfFile?->status === 'failed') - pembuatan gagal dan perlu di-retry oleh administrator.@elseif(in_array($pdfFile?->status, ['queued', 'processing'], true)) - file sedang dibuat oleh worker PDF.@endif</div></div>@if($pdfFile?->status === 'ready')<a class="btn" target="_blank" rel="noopener" href="{{ route('quotations.pdf.preview', $quotation) }}">Preview PDF</a><a class="btn btn-primary" href="{{ route('quotations.pdf.download', $quotation) }}">Download PDF</a>@endif</div></div></div>
            @endcan
        @endif
        <div class="col-lg-8"><div class="card"><div class="card-header"><h2 class="card-title">Item quotation</h2></div><div class="table-responsive"><table class="table card-table"><thead><tr><th>#</th>@foreach($quotation->item_schema['columns'] ?? [] as $column)<th>{{ $column['label'] }}</th>@endforeach</tr></thead><tbody>@foreach($quotation->items as $item)<tr><td>{{ $item->position }}</td>@foreach($item->values as $value)<td>{{ $value->value !== null && $value->value !== '' ? $value->value : '—' }}</td>@endforeach</tr>@endforeach</tbody></table></div></div>
            <div class="card mt-3"><div class="card-header"><h2 class="card-title">Terms</h2></div><div class="card-body">@forelse($quotation->terms as $term)<div class="mb-2">{{ $term->position }}. {{ $term->content }}</div>@empty<span class="text-secondary">Tidak ada terms.</span>@endforelse</div></div>
        </div>
        <div class="col-lg-4"><div class="card"><div class="card-body"><dl class="row mb-0"><dt class="col-5">Status</dt><dd class="col-7">{{ str($quotation->status)->replace('_', ' ')->headline() }}</dd><dt class="col-5">Tanggal</dt><dd class="col-7">{{ $quotation->quotation_date->format('d M Y') }}</dd><dt class="col-5">Pelanggan</dt><dd class="col-7">{{ $quotation->customer_name }}</dd><dt class="col-5">Attention</dt><dd class="col-7">{{ $quotation->attention_name ?: '—' }}</dd><dt class="col-5">Dibuat oleh</dt><dd class="col-7">{{ $quotation->creator->name }}</dd><dt class="col-5">Mata uang</dt><dd class="col-7">{{ $quotation->currency }}</dd><dt class="col-5">Nomor</dt><dd class="col-7">{{ $quotation->document?->number ?? 'Belum diterbitkan' }}</dd>@if($quotation->completed_at)<dt class="col-5">Completed</dt><dd class="col-7">{{ $quotation->completed_at->timezone(config('office.business_timezone'))->format('d M Y H:i') }}<br>{{ $quotation->completer?->name }}</dd>@endif @if($quotation->document?->voided_at)<dt class="col-5">Void</dt><dd class="col-7">{{ $quotation->document->voided_at->timezone(config('office.business_timezone'))->format('d M Y H:i') }}<br>{{ $quotation->document->voider?->name }}<div class="text-danger">{{ $quotation->document->void_reason }}</div></dd>@endif</dl></div></div></div>
        <div class="col-12"><div class="card"><div class="card-header"><h2 class="card-title">Audit trail quotation</h2></div><div class="table-responsive"><table class="table card-table table-vcenter"><thead><tr><th>Waktu</th><th>Aktor</th><th>Aksi</th><th>Perubahan</th></tr></thead><tbody>@forelse($audits as $audit)<tr><td>{{ $audit->occurred_at->timezone(config('office.business_timezone'))->format('d M Y H:i') }}</td><td>{{ $audit->actor?->name ?? 'Sistem' }}</td><td><code>{{ $audit->action }}</code></td><td><details><summary>Lihat snapshot</summary><pre class="mt-2 mb-0 text-wrap">{{ json_encode(['before' => $audit->before, 'after' => $audit->after, 'context' => $audit->context], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) }}</pre></details></td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">Belum ada audit quotation.</td></tr>@endforelse</tbody></table></div></div></div>
    </div></div></div>
@endsection
